DELETE http://localhost:3003/api/blogs/65fc5859bd9ed6d393795b78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvSG8iLCJpZCI6IjY1ZmJlZWVmNmNjMzdlZjkxNjkyOTBhYyIsImlhdCI6MTcxMTI3NjI3OX0.Q3rNDhI4em-GDiwrFLVRVguZZH9xWVLLy8KeoGFmGF4